---
- name: "Prepare Collection"
  hosts: "localhost"
  tasks:
    - name: "Run ansible-playbook"
      ansible.builtin.command: "ansible-playbook playbook.yml"
    - name: "Run ansible-galaxy"
      ansible.builtin.command: "ansible-galaxy install --force -r collections.yml"

